name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    
jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.2-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Prepare logs folder
        run: sudo mkdir -p /var/logs && sudo chmod 777 /var/logs

      - name: Run unit tests
        env:
          DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb
        run: poetry run pytest -m "not integration"


  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/github-actions-basics
            git pull origin main
            docker-compose pull
            docker-compose up -d --build
